# Generated by Django 2.2 on 2020-06-22 04:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Password', models.CharField(blank=True, max_length=256, null=True)),
                ('Mobile', models.BigIntegerField(null=True, unique=True)),
                ('Passport_No', models.CharField(blank=True, max_length=100, null=True)),
                ('DOB', models.CharField(blank=True, max_length=100, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='Images')),
            ],
        ),
        migrations.CreateModel(
            name='Login_Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logged_in', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Logged_out', models.DateTimeField(blank=True, null=True)),
                ('Ip_Address', models.CharField(blank=True, max_length=15, null=True)),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Register')),
            ],
        ),
    ]
