# Generated by Django 2.2 on 2020-06-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_session',
            name='Ip_Address',
        ),
        migrations.AddField(
            model_name='login_session',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
