# Generated by Django 2.2.1 on 2020-03-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20200310_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='types',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
